[package]
name = "airomem"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/makindotcc/airomem-rs"
categories = ["database-implementations"]
description = "Simple persistence library inspired by Prevayler and @jarekratajski"
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.10"
